name: Deploy Flutter Web to S3 and CloudFront

on:
  push:
    branches:
      - main  # This will deploy on every push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          architecture: x64

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Flutter app for web
      - name: Build Flutter Web
        run: flutter build web

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # Replace with your AWS region

      # Step 6: Deploy to S3
      - name: Sync to S3
        run: aws s3 sync ./build/web s3://my-flutter-web-app --delete
        # Replace 'your-bucket-name' with the name of your S3 bucket

      # Step 7: Invalidate CloudFront cache
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1K2R8CU467I2X --paths "/*"
        # Replace 'YOUR_DISTRIBUTION_ID' with your CloudFront distribution ID
